version: '3.7'

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - $PWD/.docker-volumes/postgres-data:/var/lib/postgresql/data
